### ISSUE TITLE
.htaccess File is Missing from Release ZIP

### ISSUE THREAD

**Issue by wildforestnorth** [Neoflow/ReverseProxy-PlausibleAnalytics#5]
FYI

It's confusing in your installation instructions, which say #1 "Manually download the latest release from here." but the ZIP file doesn't contain the .htaccess file.

Then you start talking about the .htaccess file like it is important, but the lack of inclusion of the file in the ZIP release makes it seem unimportant. Then troubleshooting needs to occur.

**Comment by Alpine418** [comment]
Thanks for your feedback, but the downloadable release has the .htaccess into it.
![grafik](https://user-images.githubusercontent.com/4191615/187947008-97927286-b8a7-4cf7-9ff9-cafaef3f924f.png)

May be you could not see it because it was hidden as dot-file. What you think?

**Comment by wildforestnorth** [comment]
Yes, you are exactly right.

I am on a Mac, and the dot files are hidden by default. I don't know why this didn't occur to me. Tunnel vision?

Anyway, thank you. You may disregard my issue.

**Comment by Alpine418** [comment]
No problem. I hope you like the proxy and it will fulfill your needs. Have a good day.
