### ISSUE TITLE
Thank you for this script!

### ISSUE THREAD

**Issue by oldrup** [Neoflow/ReverseProxy-PlausibleAnalytics#6]
Not a bug report, just feedback. I have now installed the script on four different sites, and it just works. Been using an already installed WordPress plugin I use for custom CSS and JS snippets, to add the script at the front-end footer.  I loads late in the document.

![image](https://user-images.githubusercontent.com/17141205/191493608-d76a14b7-820e-4b5d-b7c5-f41bd242a31e.png)

I run a pretty tight ship in terms of cross site scripting and I found no issues (as expected, as I'm proxying the script in a subdirectory now).  https://oldrup.dk/en/http-security-headers/

Also verified that visits are still being logged at plausible.io. The Edge browser and Bing are just great for identifying that test-visit ;)

Not much to say, but thank you for sharing this with the community, and making instructions clear and straightforward :)

Bjarne

**Comment by Alpine418** [comment]
Cool. Thank you for your thank you 😉

Enjoy the script and all the best 👍
