### ISSUE TITLE
Add server-side cache

### ISSUE THREAD

**Issue by julienmru** [Neoflow/ReverseProxy-PlausibleAnalytics#8]
Hello : )

I'm thinking of adding server side-cache (for cacheable components), do you think this is something which could prove useful or it's a waste of my time?

Thanks.

**Comment by Alpine418** [comment]
Thx for your input. I will check your pull request as soon as I have time.

**Comment by Alpine418** [comment]
Released Version 1.3.0. Please try it out and give a final feedback if everything is fine.

**Comment by julienmru** [comment]
Everything seems to be working perfectly on my end. Thanks!

However, this issue was for a **server-side cache** rather and a **client-side cache** which is already handled by my [pull request](https://github.com/Neoflow/ReverseProxy-PlausibleAnalytics/pull/7). The idea is to prevent the reverse proxy to pull again the scripts from Plausible if Plausible allows to cache them (which is the case at the moment).

**Comment by Alpine418** [comment]
Oh I'm sorry, I mixed your stuff up. 

I built the reverse proxy with one mission: To hide the origin of the plausible stats. Personally I don't want to much logic in the proxy functionality to keep the maintenance and support level low. And with the your implemented support for client side cache, I don't see a large benefit to implement a server side cache too. 

Is it ok for you?
