### ISSUE TITLE
bug when in subfolder mode and folder name exists in whitelist

### ISSUE THREAD

**Issue by bfritscher** [Neoflow/ReverseProxy-PlausibleAnalytics#9]
requestUri is computed with str_replace which replaces all occurences instead of stripping the subfolder.
/s on /s/js/scripts.js  => /jscripts.js

fix: ```$requestUri = preg_replace('/'. preg_quote($relativeUri, '/') .'/', '', $_SERVER['REQUEST_URI'], 1);```

But there might be a better php way to do it.

**Comment by Alpine418** [comment]
Thx for the issue. I've fixed it.
